spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  jpa:
    generate-ddl: true
    show-sql: true
