spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    locale-resolver: fixed
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  jpa:
    generate-ddl: true

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev
  http:
    log-request-details: true
server:
  error:
    include-exception: true
    include-stacktrace: on_trace_param

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: username
    password: password
